// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsIVAOPysg9rvRTAyaF9gi5Ab3MMP0v8M',
    appId: '1:946031418647:web:956449a889723a9707ab52',
    messagingSenderId: '946031418647',
    projectId: 'rootally-ai-assignment',
    authDomain: 'rootally-ai-assignment.firebaseapp.com',
    storageBucket: 'rootally-ai-assignment.appspot.com',
    measurementId: 'G-4GWF18WZ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPSoXvqowaclXp8UyDfeb4UFa1xErKjE',
    appId: '1:946031418647:android:af178ab9b676e58707ab52',
    messagingSenderId: '946031418647',
    projectId: 'rootally-ai-assignment',
    storageBucket: 'rootally-ai-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6c_R6NM42_2AqUkQP9VlYASHXsiO9vIo',
    appId: '1:946031418647:ios:9858e89eaee33d8907ab52',
    messagingSenderId: '946031418647',
    projectId: 'rootally-ai-assignment',
    storageBucket: 'rootally-ai-assignment.appspot.com',
    iosClientId: '946031418647-ptvtrkba6647gv4ebvlldecno0fo8n1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.rootllyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6c_R6NM42_2AqUkQP9VlYASHXsiO9vIo',
    appId: '1:946031418647:ios:9858e89eaee33d8907ab52',
    messagingSenderId: '946031418647',
    projectId: 'rootally-ai-assignment',
    storageBucket: 'rootally-ai-assignment.appspot.com',
    iosClientId: '946031418647-ptvtrkba6647gv4ebvlldecno0fo8n1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.rootllyai',
  );
}
